[tool.poetry]
name = "lh-django"
version = "0.1.0"
description = ""
authors = ["Segelzwerg <25705862+Segelzwerg@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"
django-embed-video = "^1.4.9"
setuptools = "^69.1.1"
google-api-python-client = "^2.121.0"
httpx = "^0.27.0"
pillow = "^10.2.0"
django-bootstrap5 = "^23.4"
django-compressor = "^4.4"
django-libsass = "^0.9"


[tool.poetry.group.dev.dependencies]
pylint = "^3.1.0"
coverage = "^7.4.3"
flake8 = "^7.0.0"
pylint-django = "^2.5.5"
bandit = "^1.7.8"
factory-boy = "^3.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.bandit]
exclude_dirs = ["*/tests.py"]