[tool.poetry]
name = "lh-django"
version = "0.1.0"
description = ""
authors = ["Segelzwerg <25705862+Segelzwerg@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"
django-embed-video = "^1.4.9"
setuptools = "^69.0.2"


[tool.poetry.group.dev.dependencies]
pylint = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
