[tool.poetry]
name = "lh-django"
version = "0.1.0"
description = ""
authors = ["Segelzwerg <25705862+Segelzwerg@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
