name: License Checker

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - name: Install poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true
                virtualenvs-in-project: true

            - name: Load cached venv
              uses: actions/cache@v4
              with:
                path: .venv
                key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

            - name: Install dependencies
              shell: bash
              run: poetry install --no-interaction

            - name: Freeze Dependencies
              shell: bash
              run: poetry export --without-hashes --format=requirements.txt > requirements.txt

            - name: Check Licenses
              shell: bash
              id: license-check
              run: echo "LICENSE=$(poetry run liccheck -s .liccheck.ini -r requirements.txt)" >> "$GITHUB_OUTPUT"
