name: License Checker

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - name: Install poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true
                virtualenvs-in-project: true

            - name: Load cached venv
              uses: actions/cache@v4
              with:
                path: .venv
                key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

            - name: Install dependencies
              shell: bash
              run: poetry install --no-interaction

            - name: Freeze Dependencies
              shell: bash
              run: poetry export --without-hashes --format=requirements.txt > requirements.txt

            - name: Check Licenses
              shell: bash
              id: license-check
              run: |
                AUTHORIZED=$(poetry run liccheck -s .liccheck.ini -r requirements.txt | grep -A 1 "check authorized packages" | grep -vE "packages..." | grep -oP "^\S+" || echo "0")
                UNKNOWN=$(poetry run liccheck -s .liccheck.ini -r requirements.txt | grep -A 1 "check unknown package"s | grep -vE "packages..." | grep -oP "^\S+" || echo "0")
                UNAUTHORIZED=$(poetry run liccheck -s .liccheck.ini -r requirements.txt | grep -A 1 "check unauthorized packages" | grep -vE "packages..." | grep -oP "^\S+" || echo "0")
                echo "AUTHORIZED_PACKAGES=$AUTHORIZED" >> "$GITHUB_OUTPUT"
                echo "UNKNOW_PACKAGES=$UNKNOWN" >> "$GITHUB_OUTPUT"
                echo "UNAUTHORIZED_PACKAGES=$UNAUTHORIZED" >> "$GITHUB_OUTPUT"

            - name: License Unauthorized
              uses: actions/github-script@v3
              if: ${{ steps.license-check.outputs.UNAUTHORIZED_PACKAGES >= 0}}
              with:
                script: |
                    core.setFailed('${{ steps.license-check.outputs.UNAUTHORIZED_PACKAGES }} unauthorized packages found.')

            - name: License Unknown
              uses: actions/github-script@v3
              if: ${{ steps.license-check.outputs.UNKNOWN_PACKAGES >= 0}}
              with:
                script: |
                    core.setFailed('${{ steps.license-check.outputs.UNKNOWN_PACKAGES }} unknown packages found.')