name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: Whist-Team/actions/setup-poetry@v2
        with:
          python-version: 3.12

      - name: Lint sources with flake8
        run: poetry run flake8 lh_django --count --show-source --statistics

      - name: Lint sources with pylint
        run: poetry run pylint lh_django

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run bandit
        uses: tj-actions/bandit@v5
        with:
          targets: |
            lh_django
          options: "-r"
